# 项目相关配置
ruoyi:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: C:\Users\Administrator\Desktop\taisu\upload
  machine: A
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8090

plchlk:
  host: http://192.168.10.45:11116
dingyue:
  host: http://192.168.10.45:80/prod-api/api/warn/addWarnInfo
#中心库地址
cent:
  host: http://127.0.0.1:8090
# 厂区编号
#factoryCode: AE


spring:
  redis:
    host: 192.168.10.45
    port: 36652
    password:
    database: 0
    # 连接超时时间
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      # 主库数据源
      master:
        url: jdbc:sqlserver://192.168.10.15:1433;DatabaseName=taisu-center-cen
        username: sa
        password: '*A23A1C66AABC5165074F3EDFEF866BC67FAD047F'
        # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:sqlserver://192.168.10.15:1433;DatabaseName=taisu-transit-test
        username: transit
        password: tsdz@2022
      # 定时器数据源
      iemdg:
        enabled: true
        url: jdbc:sqlserver://10.217.33.38:1433;DatabaseName=IEMDG
        username: faceid
        password: faceid
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# 日志配置
logging:
  level:
    com.ruoyi: error
    org.springframework: warn


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  #pathMapping: /prod-api
  pathMapping: /
